DROP DATABASE IF EXISTS medic_database;

CREATE DATABASE medic_database;
USE medic_database;

CREATE TABLE USUARIO(
    id INT NOT NULL AUTO_INCREMENT,
    cui INT NOT NULL,
    tipo VARCHAR(40) NOT NULL,
    nombre VARCHAR(40) NOT NULL,
    nombre_usuario VARCHAR(40) NOT NULL,
    contraseña VARCHAR(40) NOT NULL,
    direccion VARCHAR(40) NOT NULL,
    correo_electronico VARCHAR(40) NOT NULL,
    fecha_de_nacimiento VARCHAR(40) NOT NULL,
    saldo DECIMAL NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE RECARGAS(
    cui INT NOT NULL,
    fecha VARCHAR(40) NOT NULL,
    saldo INT NOT NULL
);

CREATE TABLE MEDICO(
    id INT NOT NULL AUTO_INCREMENT,
    cui INT NOT NULL,
    especialidad VARCHAR(40) NOT NULL,
    costo DECIMAL NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT FK_IDMEDICO FOREIGN KEY(id)
    REFERENCES USUARIO(id)
);



CREATE TABLE ESPECIALIDAD(
    id INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(40) NOT NULL,
    descripcion VARCHAR(40) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE PORCENTAJE(
    id INT NOT NULL AUTO_INCREMENT,
    fecha VARCHAR(40) NOT NULL,
    porcentaje DECIMAL(10,2) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE ESPECIALIDADMEDICO(
    id INT NOT NULL AUTO_INCREMENT,
    cui INT NOT NULL,
    costo DECIMAL NOT NULL,
    nombre VARCHAR(40) NOT NULL,
    descripcion VARCHAR(40) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE ESPECIALIDADADMIN(
    id INT NOT NULL AUTO_INCREMENT,
    cui INT NOT NULL,
    costo DECIMAL NOT NULL,
    nombre VARCHAR(40) NOT NULL,
    descripcion VARCHAR(40) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE LABORATORIO(    
    id INT NOT NULL AUTO_INCREMENT,
    cui INT NOT NULL,
    tipo_examen VARCHAR(40) NOT NULL,
    costo DECIMAL NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT FK_IDLAB FOREIGN KEY(id)
    REFERENCES USUARIO(id)
);

CREATE TABLE CONSULTA(
    id INT NOT NULL AUTO_INCREMENT,
    fecha_inicio VARCHAR(40) NOT NULL,
    fecha_fin VARCHAR(40) NOT NULL,
    estado VARCHAR(40) NOT NULL,
    porcentaje DECIMAL(5,2) NOT NULL,
    paciente INT NOT NULL,
    medico VARCHAR(40) NOT NULL,
    costo DECIMAL(10,2) NOT NULL,
    especialidad VARCHAR(40) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE EXAMEN(
    id INT NOT NULL AUTO_INCREMENT,
    fecha_solicitud VARCHAR(40) NOT NULL,
    fecha_fin VARCHAR(40) NOT NULL,
    estado VARCHAR(40) NOT NULL,
    paciente INT NOT NULL,
    laboratorio VARCHAR(40) NOT NULL,
    examen VARCHAR(40) NOT NULL,
    porcentaje DECIMAL(5,2) NOT NULL,
    costo DECIMAL(10,2) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE EXAMENLABORATORIO(
    id INT NOT NULL AUTO_INCREMENT,
    cui INT NOT NULL,
    nombre VARCHAR(40) NOT NULL,
    costo DECIMAL NOT NULL,
    descripcion VARCHAR(40) NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT FK_IDLABEXAM FOREIGN KEY(id)
    REFERENCES USUARIO(id)
);


CREATE TABLE TIPOEXAMEN(
    id INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(40) NOT NULL,
    descripcion VARCHAR(40) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE TIPOEXAMENADMIN(
    id INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(40) NOT NULL,
    costo INT NOT NULL,
    descripcion VARCHAR(40) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE COSTOEXAMEN(
    id INT NOT NULL AUTO_INCREMENT,
    costo DECIMAL NOT NULL,
    PRIMARY KEY(id), 
    CONSTRAINT FK_IDLABCOSTO FOREIGN KEY(id)
    REFERENCES TIPOEXAMEN(id)
);

CREATE TABLE EXAMENCOSTO(
    id INT NOT NULL,
    cui INT NOT NULL,
    costo DECIMAL NOT NULL
    
);


